name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4  # Upgraded to v4 for Node.js 20 support
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4  # Example for artifact storage
        if: success()
        with:
          name: build-artifacts
          path: build
